### ISSUE TITLE
No profiles found

### ISSUE THREAD

**Issue by astroboii47** [Garulf/Wallpaper-Engine-Profile-Selector#2]
Would love to use this plugin but no matter what I do I always get "No profiles found". I think it might be something related to Flox or the way profiles are stored :\

**Comment by Garulf** [comment]
Hello @aaronkim98,

Wallpaper engine has 3 different modes that can be confused with profiles. The best way to show you which ones this plugin supports is to show you a screenshot. I'll post one here when I'm able to get back to my desktop.

**Comment by astroboii47** [comment]
Ahh I see, thank you so much that would be amazing! I've been playing around with playlists, presets and profiles but a screenshot would definitely help me out :)

**Comment by Garulf** [comment]
Hope this helps:

![image](https://user-images.githubusercontent.com/535299/209492728-eab410e5-8a26-4189-8614-ab9cac8b1f34.png)

![image](https://user-images.githubusercontent.com/535299/209492761-6ae6763a-f401-4678-b7f5-606207722c75.png)

Should pull them up like so:

![image](https://user-images.githubusercontent.com/535299/209492805-6d9246dc-2b15-4167-bf87-70d9219629f1.png)

**Comment by astroboii47** [comment]
Ahh ok, thank you helps!! I am definitely using that option, but I do have multiple monitors - could that possibly be affecting it?

**Comment by Garulf** [comment]
No im using dual monitors just stretched. Is your version of Wallpaper Engine on Steam or else where?

**Comment by astroboii47** [comment]
My Wallpaper Engine is version: Build 2.2.18 from Steam, using the wallpaper32.exe and it's installed at C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine

Thanks so much for your help :)

**Comment by Garulf** [comment]
Settings set to the correct path?

![image](https://user-images.githubusercontent.com/535299/209493426-16d72a23-71a2-4254-ab39-a3a62da57c71.png)

**Comment by astroboii47** [comment]
Yep, I set settings to the exact path, also tried editing the default value to fall back to that path. My Flow launcher is version 1.10.1 just in case that is different

**Comment by astroboii47** [comment]
I did just realise that my plugin is on version 0,0.2 instead of 0.1.0
![Snipaste_2022-12-26_13-53-54](https://user-images.githubusercontent.com/58410541/209493769-e1f3f7ed-a747-4675-b077-b4324de28f60.png)

**Comment by Garulf** [comment]
My version is an unreleased version. Nothing really changed beside some library updates.

**Comment by astroboii47** [comment]
Ahh I see, no problem! Yeah I'm definitely lost as to why it can't find my profiles - the only thing left I can think of is something to do with maybe the spaces between "Program Files (x86)", or my account username being "ABC" somehow affecting how the profiles are stored

![Snipaste_2022-12-26_14-07-47](https://user-images.githubusercontent.com/58410541/209495519-19ba8030-cfa3-478b-b9bc-476ddb3d99e9.png)

![Snipaste_2022-12-26_14-07-26](https://user-images.githubusercontent.com/58410541/209495527-4773e287-a336-472d-ab6c-66abffd92d58.png)

**Comment by Garulf** [comment]
Ah! Interesting... The key used for my profiles *is* plural while yours's is singular.

Notice my config uses "profiles":
![image](https://user-images.githubusercontent.com/535299/209566549-8ebe437e-41aa-4f55-90b7-3095d393472a.png)

Very strange way to do a config... anyway could you try adding multiple profiles or manually changing your "profile" key to "profiles"?

**Comment by Garulf** [comment]
Could you please link your entire config file?

**Comment by astroboii47** [comment]
Sure I was just about to say maybe linking it here would be easier! It won't let me attach a json so I just zipped it
It seems as though I have plural "profiles" in one spot but singular inside, and then a "groups" category that makes up most of the space inside

Even when I choose to stretch the wallpaper across all monitors, a group is still made 
[config.zip](https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/files/10304116/config.zip)

**Comment by Garulf** [comment]
Okay I believe I fixed the issue. it was some poorly written logic on my end that was the issue.

![image](https://user-images.githubusercontent.com/535299/209571437-cced9964-65bd-4cc3-9964-859e57b8d51c.png)

I have a fix ready here: https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/pull/3

Please give it a test by downloading it here: 
[artifact.zip](https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/files/10304352/artifact.13.zip)

You can have Flow Launcher install it for you by typing:
```
pm install https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/files/10304352/artifact.13.zip
```

**Comment by astroboii47** [comment]
Thank you so much for all your help 😊 - it definitely appears perfectly now, but pressing enter doesn't seem to apply the selected wallpaper (just tried for each one)

**Comment by astroboii47** [comment]
Managed to fix it by adding quotation marks to this part in wallpaper_engine.py: 
![Snipaste_2022-12-27_10-07-37](https://user-images.githubusercontent.com/58410541/209587723-364ae507-51ff-4c9d-a1d1-13d0ca52bd6a.png)

Working super well now - really appreciate it! you're the best :))
